LangString addOrReinstall ${LANG_SPANISH} "Añadir o reinstalar componentes"
LangString alreadyInstalled ${LANG_SPANISH} "Ya está instalado"
LangString alreadyInstalledLong ${LANG_SPANISH} "${PRODUCTNAME} ${VERSION} ya está instalado. Elige qué quieres hacer y pulsa Siguiente."
LangString appRunning ${LANG_SPANISH} "${PRODUCTNAME} está abierto. Ciérralo e inténtalo de nuevo."
LangString appRunningOkKill ${LANG_SPANISH} "${PRODUCTNAME} está abierto.$\nPulsa Aceptar para cerrarlo y continuar."
LangString chooseMaintenanceOption ${LANG_SPANISH} "Elige qué quieres hacer con la instalación actual."
LangString choowHowToInstall ${LANG_SPANISH} "Elige cómo quieres instalar ${PRODUCTNAME}."
LangString createDesktop ${LANG_SPANISH} "Crear un acceso directo en el escritorio"
LangString dontUninstall ${LANG_SPANISH} "No desinstalar"
LangString dontUninstallDowngrade ${LANG_SPANISH} "No desinstalar (este instalador no permite volver a una versión anterior sin desinstalar)"
LangString failedToKillApp ${LANG_SPANISH} "No se pudo cerrar ${PRODUCTNAME}. Ciérralo e inténtalo de nuevo."
LangString installingWebview2 ${LANG_SPANISH} "Instalando WebView2 (necesario para la app)…"
LangString newerVersionInstalled ${LANG_SPANISH} "Ya tienes instalada una versión más reciente de ${PRODUCTNAME}. Si de verdad quieres esta versión anterior, desinstala primero la actual. Elige qué quieres hacer y pulsa Siguiente."
LangString older ${LANG_SPANISH} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_SPANISH} "Tienes instalada la versión $R4 de ${PRODUCTNAME}. Te recomendamos desinstalarla antes de continuar. Elige qué quieres hacer y pulsa Siguiente."
LangString silentDowngrades ${LANG_SPANISH} "Este instalador no permite volver a una versión anterior en modo silencioso. Usa el instalador normal.$\n"
LangString unableToUninstall ${LANG_SPANISH} "No se pudo desinstalar."
LangString uninstallApp ${LANG_SPANISH} "Desinstalar ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SPANISH} "Desinstalar antes de instalar"
LangString unknown ${LANG_SPANISH} "desconocida"
LangString webview2AbortError ${LANG_SPANISH} "No se pudo instalar WebView2. Vuelve a abrir el instalador."
LangString webview2DownloadError ${LANG_SPANISH} "Error: no se pudo descargar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SPANISH} "WebView2 se descargó correctamente."
LangString webview2Downloading ${LANG_SPANISH} "Descargando WebView2…"
LangString webview2InstallError ${LANG_SPANISH} "Error: la instalación de WebView2 falló con el código $1."
LangString webview2InstallSuccess ${LANG_SPANISH} "WebView2 se instaló correctamente."
LangString deleteAppData ${LANG_SPANISH} "Eliminar también los datos de la app (sesión y preferencias)"
